### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by AnujSsStw** [nhcommunity/community#100]
### Why do you want to join our organization?

- Learn in public 
- Can help others and get help for projects and stuff
- Be a part of a community that helps each other
- Build a network with amazing forks
- And maybe collab on projects

**Comment by nhcarrigan** [comment]
Invite sent!

**Comment by AnujSsStw** [comment]
## Thanks 😍
I think it's going to be great finally being a party of community
