### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by bishal7679** [nhcommunity/community#122]
### Why do you want to join our organization?

It feels really awesome to see the community grow & being a part of it, along this journey. 
Looking forward to helping this community in whichever way I can & contribute to the cause of learning & empowering others 🙂

**Comment by bishal7679** [comment]
@nhcarrigan are you there?

**Comment by nhcarrigan** [comment]
Invite sent!

**Comment by bishal7679** [comment]
@nhcarrigan thanks a lot : )
