### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by cixtor** [nhcommunity/community#158]
### Why do you want to join our organization?

The initiative to bring developers together to collaborate on different projects sounds wonderful. I have been an active member of the open-source community on GitHub and other platforms, and it is always a joy to find like-minded people willing to share knowledge and experiences. I would love to join thir GitHub organization to help many more developers become excellent open-source maintainers.

**Comment by naomi-lgbt** [comment]
Invite sent!
