### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by naman1102** [nhcommunity/community#180]
### Why do you want to join our organization?

My name is Naman, I am in the Third year of my graduation, and Aspiring engineer and problem solver, who likes to work on different stacks, till now worked on C# C++ python MERN Flutter + Firebase and now finally want to start my open source journey, Also I am geeks for geeks student chapter AITR Indore Indore, Co-lead, I want to join the organization  to start my open source and contributing career

**Comment by naomi-lgbt** [comment]
Forgot to close this whoops!
