### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by anekemichael** [nhcommunity/community#202]
### Why do you want to join our organization?

I'm sorry guys but the invite link is not working.

**Comment by naomi-lgbt** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/63889819/190296408-ee64c198-ae51-49da-804c-ff0029f1a585.png">

Hi you are already a member.

**Comment by anekemichael** [comment]
Thanks so much..
