### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by DevStar0202** [nhcommunity/community#209]
### Why do you want to join our organization?

I am crazy about this community.
And I love teamwork with the others all over the world and I really wanna be one of your teammates.

Thanks.

**Comment by DevStar0202** [comment]
My name is Daivid morgan.
I am from Macedonia.
Please invite me.

**Comment by DevStar0202** [comment]
Let's contribute some new project with me.

Thanks. Daivid.

**Comment by naomi-lgbt** [comment]
Invite sent
