### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by WebSpecialist2021** [nhcommunity/community#219]
### Why do you want to join our organization?

I'd like to learn and contribute myself for the nhcommunity.

**Comment by naomi-lgbt** [comment]
Invite sent~!

**Comment by WebSpecialist2021** [comment]
> Invite sent~!

Thank you @naomi-lgbt

**Comment by devlancer-lucas** [comment]
I want to join to your ORG!!!

**Comment by naomi-lgbt** [comment]
Heya @devlancer-lucas - please [open your own issue](https://github.com/naomis-novas/community/issues/new?assignees=naomi-lgbt&labels=%E2%9C%89%EF%B8%8F+misc%3A+invite+to+org&projects=&template=join_org.yml&title=%5BORG%5D+Invite+me+to+the+organization) to get the invitation.
