### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by namangirdhar16** [nhcommunity/community#39]
### Why do you want to join our organization?

I'm a newbie to the world of open source, recently i started my journey through the mode of hacktoberfest so far i have got my 2 PRs merge but it gave me an immense happiness, i came to know about this organization through @eddiejaoude. I would like to contribute to your organization in any possible way and i want myself to grow with the community. I would like to learn from this organization and help other peers in any way possible.

**Comment by nhcarrigan** [comment]
Invite sent!

**Comment by namangirdhar16** [comment]
@nhcarrigan i can't see invite anywhere?

**Comment by nhcarrigan** [comment]
Should be in your email.

**Comment by namangirdhar16** [comment]
@nhcarrigan i will check again.

**Comment by namangirdhar16** [comment]
@nhcarrigan i am getting email regarding this chat but not any invite.
