### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcommunity/community#4]
We should update the issue templates on this repository. Since it'll be a community resource, and not a code project, we can include issue templates for things like getting support, joining the organisation, and similar events.

**Comment by galahad42** [comment]
For anyone new to making issue templates can follow [this guide](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by srisatya1197** [comment]
@nhcarrigan I want to give it a shot.

**Comment by nhcarrigan** [comment]
Go for it!

**Comment by prathamesh-borse** [comment]
@nhcarrigan I wanted to work on this issue and also I would know which type of issue template we have to add to this Repository.

**Comment by nhcarrigan** [comment]
I think we should add an issue template for folks who want to join the organisation, as a first step.

Note that we are using the new GitHub issue forms for this.

**Comment by prathamesh-borse** [comment]
Okay, can I create that issue template, and also can you share the resource on how can I create the new issue template.

**Comment by prathamesh-borse** [comment]
> I think we should add an issue template for folks who want to join the organization, as a first step.
> 
> Note that we are using the new GitHub issue forms for this.

@nhcarrigan I have created the issue template but don't able to know what we should write in the template content field could you please elaborate on that.

**Comment by prathamesh-borse** [comment]
> I think we should add an issue template for folks who want to join the organization, as a first step.
> 
> Note that we are using the new GitHub issue forms for this.

@nhcarrigan Is this correct?

![Issuetemplate](https://user-images.githubusercontent.com/66899360/127266813-5079c5b8-7612-4652-a399-4037a0273cbf.png)

**Comment by nhcarrigan** [comment]
That looks good - you should add me to the `assignees`, and add a `textarea` field that asks folks to explain why they want to join,

**Comment by prathamesh-borse** [comment]
In the assignee's section, do I have to add myself or another?

**Comment by prathamesh-borse** [comment]
@nhcarrigan Can u please check this #7 This PR and do let me know what changes I have to make in that issue Template.

**Comment by Panquesito7** [comment]
We could include the same issue templates/forms from the other repositories. What do you think? 🙂

**Comment by nhcarrigan** [comment]
We should already have the standard ones in place.

**Comment by prathamesh-borse** [comment]
@nhcarrigan Updated this issue template #7  with requested changes can u please check now?

**Comment by prathamesh-borse** [comment]
@nhcarrigan Is there any issue that can be improved in this organization and also one small request for @nhcarrigan can I join this organization for making more contributions.!

**Comment by krishguptadev** [comment]
Can I fix this issue if it isn't fixed yet?

**Comment by nhcarrigan** [comment]
I can't think of any other templates we need off hand. Any ideas?

**Comment by krishguptadev** [comment]
Then maybe you forgot to close this issue 🤷‍♂️

**Comment by nhcarrigan** [comment]
Leaving it open as a point of discussion. 🙂

**Comment by naomi-lgbt** [comment]
Going to close this for now.
