### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [nhcommunity/community#42]
### Why do you want to join our organization?

I'm an Web Dev Enthusiasts & a junior pursuing my Bachelors in Computer Science & Engineering. I'm interested in Web Devlopment, Android Devlopment, IOS Devlpoment, Machine Learning & Devops & I enjoy learning new things & stuff as well as I'm a Frontend Devloper with experience building Dynamic & Static Web pages. I am always interested in learning the answers to how, why and what relating to Technologies around me.

I would like to grow my programming skills by doing lot's of  Open Source Contribution. Looking forward to learn, collabrate and grow as a community.

**Comment by nhcarrigan** [comment]
Invite sent!
