### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by thuongtruong1009** [nhcommunity/community#47]
### Why do you want to join our organization?

I'm a student with open-source code love.
Currently, exploring will help me learn more and more with everyone globally.
Thanh you very much!

**Comment by krishguptadev** [comment]
Welcome to the Community!

**Comment by thuongtruong1009** [comment]
> Welcome to the Community!

Thank you very much!
But I haven't received your invitation email.

**Comment by krishguptadev** [comment]
> > Welcome to the Community!
> 
> Thank you very much! But I haven't received your invitation email.

It would be available once @nhcarrigan adds the invitation label 🙂 Thanks for being patient

**Comment by nhcarrigan** [comment]
Invite sent!
