### ISSUE TITLE
[FEAT] - Verify the organization's domain

### ISSUE THREAD

**Issue by Panquesito7** [nhcommunity/community#6]
### What feature would you like to see?

Verify the organization's domain (see the [GitHub Docs](https://docs.github.com/en/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization)).

### Additional information

With the organization verification, everyone will know that nhcommunity controls the domain `chat.nhcarrigan.com` and that it's not a fake or copy-pasta organization. IMO, it will also make the organization look cooler with that `Verified` badge.

Let me know what do you think. Thanks. 🙂

**Comment by nhcarrigan** [comment]
I'm not sure that subdomains can be verified. Let me look in to this.

**Comment by nhcarrigan** [comment]
Done 🙂

**Comment by Panquesito7** [comment]
Thank you! 😄
