### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by JayantGoel001** [nhcommunity/community#8]
### Why do you want to join our organization?

To Contribute Toward open source and become a better developer.

**Comment by nhcarrigan** [comment]
Hi there,

Please update your issue to include a description of why you want to join our organisation. 🙂

**Comment by JayantGoel001** [comment]
> Hi there,
> 
> Please update your issue to include a description of why you want to join our organisation. 🙂

Hello @nhcarrigan 
I just Updated the description.
Thank You.

**Comment by nhcarrigan** [comment]
Invite sent!
