### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by Asmit2952** [nhcommunity/community#91]
### Why do you want to join our organization?

Hello I am Asmit Malakannawar, a sophomore pursuing CSE, nhcommunity seems like an interesting open-source community to collaborate and hangout with. I want to contribute and make connections with like minded people. Also I am a beginner finding my way through open-source so this community will help me achieve my goals.

**Comment by nhcarrigan** [comment]
Invite sent!
