### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by iamrahulmahato** [nhcommunity/community#94]
### Why do you want to join our organization?

The reason why I want to join the community because of the following reasons:

1. This community basically target the beginner who enters to open source which I like most
2. As a full-stack developer when I enter open source I face many problems and till now I am learning so the mistake I have
    early I don't want others will repeat so if I join the community I can help them to don't repeat that mistake
3. As a student I am learning only and if I get to join the community I think I will learn more and grow

**Comment by nhcarrigan** [comment]
Invite sent!
