### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by 0x30c4** [nhcommunity/community#95]
### Why do you want to join our organization?

    This community basically target the beginner who enters to open source which I like most
    As a full-stack developer when I enter open source I face many problems and till now I am learning so the mistake I have
    early I don't want others will repeat so if I join the community I can help them to don't repeat that mistake
    As a student I am learning only and if I get to join the community I think I will learn more and grow

**Comment by nhcarrigan** [comment]
Invite sent!
