### ISSUE TITLE
[BUG] - Discord Link Expired

### ISSUE THREAD

**Issue by kaal-coder** [nhcommunity/community#99]
### What bug did you encounter?

The bug is here - https://github.com/nhcommunity/homepage/edit/main/README.md
In line number 33.

### What did you expect to happen?

The link was expected to open the discord server, but the link has expired.
I request the owner to update it ASAP.
And if possible add me in the organisation . 
Thanks in advance
kaushik.lakhani1232gmail.com

### Screenshots

![discord link not working](https://user-images.githubusercontent.com/85815858/160871038-6c107fa1-096b-4b6b-ad10-326d676ec61e.png)

### Additional information

You can get a discord joining permanent link in the settings.
If you aren't able to find, just google the same how to get a permanent joining link.

**Comment by nhcarrigan** [comment]
Ah, Discord killed the invite when I restructured the server. Updated the Cloudflare Worker with a new link so this should be resolved now.
